### ISSUE TITLE
Create the main Boole Bots Game page

### ISSUE THREAD

**Issue by giangpham-cfg** [chingu-voyages/v44-tier2-team-18#16]
**__Feature Description__**
As an user, I want to play the Boole Bots game within a single webpage
So I don’t have to learn a complex app and so I can quickly play the game without being distracted

**__Major User Stories/tasks__**
- [ ] User can see configuration panel and start to configure the bots to play the game
- [ ] User can click on a button to control the game
- [ ] User can see how the bots moving and colliding inside the game arena
- [ ] User can see the results of the game on the leaderboard

**__Additional Considerations__**
The page should not reload
The app must be responsive when running on all types of screen sizes - phone, tablet, laptop, desktop
